apiVersion: v1
kind: Service
metadata:
  name: hellokube
spec:
  selector:
    app: hellokube
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: ClusterIP
